apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gh-flow-demo
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: gh-flow
    server: https://kubernetes.default.svc
  source:
    path: kubernetes
    repoURL: https://github.com/e-commander/gh-flow
    targetRevision: dev
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
    - CreateNamespace=true