apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: temp-demo
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: temp
    server: https://kubernetes.default.svc
  source:
    path: kubernetes
    repoURL: https://github.com/e-commander/temp
    targetRevision: main
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
    - CreateNamespace=true