apiVersion: apps/v1
kind: Deployment
metadata:
  name: temp-demo
  labels:
    app: temp-demo
    app.kubernetes.io/name: temp-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temp-demo
  template:
    metadata:
      labels:
        app: temp-demo
    spec:
      nodeSelector:
        nodegroup: tools
      containers:
        - name: temp-demo
          image: 123456789310.dkr.ecr.us-west-1.amazonaws.com/temp
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          resources:
            requests:
              cpu: 64m
              memory: 64Mi
            limits:
              cpu: 128m
              memory: 128Mi
          startupProbe:
            httpGet:
              path: /healthz
              port: 8000
            failureThreshold: 30
            periodSeconds: 1
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
          envFrom:
            - secretRef:
                name: temp-demo-secrets
            - configMapRef:
                name: temp-demo-cm
