apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: temp-demo
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: temp-demo-secrets
    creationPolicy: Owner
  data:
    - secretKey: temp-demo
      remoteRef:
        key: temp-dev # aws secret manager name
        property: temp-demo # aws secret_key
