apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gh-flow-demo
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: gh-flow-demo-secrets
    creationPolicy: Owner
  data:
    - secretKey: gh-flow-demo
      remoteRef:
        key: gh-flow-dev # aws secret manager name
        property: gh-flow-demo # aws secret_key
